enum ActivityActionTypes {
  GET_ACTIVITIES = "GET_ACTIVITIES",
  SET_CURRENT_ACTIVITY = "SET_CURRENT_ACTIVITY",
  CLEAR_CURRENT_ACTIVITY = "CLEAR_CURRENT_ACTIVITY",
  CREATE_ACTIVITY = "CREATE_ACTIVITY",
  UPDATE_ACTIVITY = "UPDATE_ACTIVITY",
  DELETE_ACTIVITY = "DELETE_ACTIVITY"
}

export default ActivityActionTypes;
